/**
 * Unit definitions, categories, and formulas for unitfyi.
 *
 * 200 units across 20 measurement categories with numeric conversion factors.
 */

import type { UnitDef, CategoryDef, TemperatureFormula } from "./types.js";

// ---------------------------------------------------------------------------
// All unit definitions (200 units, 20 categories)
// ---------------------------------------------------------------------------

export const UNITS: Record<string, UnitDef> = {
  // ======================================================================
  // 1. LENGTH (base: meter)
  // ======================================================================
  "meter": {
    name: "Meter",
    symbol: "m",
    category: "length",
    toBase: 1,
    description: "SI base unit of length",
    aliases: ["metre", "meters", "metres"],
  },
  "kilometer": {
    name: "Kilometer",
    symbol: "km",
    category: "length",
    toBase: 1000,
    description: "1,000 meters",
    aliases: ["kilometre", "kilometers", "kilometres"],
  },
  "centimeter": {
    name: "Centimeter",
    symbol: "cm",
    category: "length",
    toBase: 0.01,
    description: "One hundredth of a meter",
    aliases: ["centimetre", "centimeters", "centimetres"],
  },
  "millimeter": {
    name: "Millimeter",
    symbol: "mm",
    category: "length",
    toBase: 0.001,
    description: "One thousandth of a meter",
    aliases: ["millimetre", "millimeters", "millimetres"],
  },
  "micrometer": {
    name: "Micrometer",
    symbol: "\u00b5m",
    category: "length",
    toBase: 0.000001,
    description: "One millionth of a meter",
    aliases: ["micrometre", "micron", "micrometers"],
  },
  "nanometer": {
    name: "Nanometer",
    symbol: "nm",
    category: "length",
    toBase: 0.000000001,
    description: "One billionth of a meter",
    aliases: ["nanometre", "nanometers", "nanometres"],
  },
  "mile": {
    name: "Mile",
    symbol: "mi",
    category: "length",
    toBase: 1609.344,
    description: "Imperial/US unit equal to 5,280 feet",
    aliases: ["miles", "statute mile"],
  },
  "yard": {
    name: "Yard",
    symbol: "yd",
    category: "length",
    toBase: 0.9144,
    description: "Imperial unit equal to 3 feet",
    aliases: ["yards", "yds"],
  },
  "foot": {
    name: "Foot",
    symbol: "ft",
    category: "length",
    toBase: 0.3048,
    description: "Imperial unit equal to 12 inches",
    aliases: ["feet", "ft"],
  },
  "inch": {
    name: "Inch",
    symbol: "in",
    category: "length",
    toBase: 0.0254,
    description: "Imperial unit equal to 1/12 of a foot",
    aliases: ["inches", "in", '"'],
  },
  "nautical-mile": {
    name: "Nautical Mile",
    symbol: "nmi",
    category: "length",
    toBase: 1852,
    description: "Navigation unit based on Earth's circumference",
    aliases: ["nautical miles", "NM", "nmi"],
  },
  "light-year": {
    name: "Light-year",
    symbol: "ly",
    category: "length",
    toBase: 9460730472580800,
    description: "Distance light travels in one Julian year",
    aliases: ["light year", "light-years", "lightyear"],
  },
  "fathom": {
    name: "Fathom",
    symbol: "ftm",
    category: "length",
    toBase: 1.8288,
    description: "Nautical unit equal to 6 feet",
    aliases: ["fathoms", "ftm"],
  },
  "furlong": {
    name: "Furlong",
    symbol: "fur",
    category: "length",
    toBase: 201.168,
    description: "Unit equal to 1/8 of a mile (660 feet)",
    aliases: ["furlongs"],
  },
  "chain": {
    name: "Chain",
    symbol: "ch",
    category: "length",
    toBase: 20.1168,
    description: "Surveying unit equal to 66 feet",
    aliases: ["chains", "gunter's chain"],
  },
  "rod": {
    name: "Rod",
    symbol: "rd",
    category: "length",
    toBase: 5.0292,
    description: "Surveying unit equal to 16.5 feet",
    aliases: ["rods", "perch", "pole"],
  },
  "league": {
    name: "League",
    symbol: "lea",
    category: "length",
    toBase: 4828.032,
    description: "Historical unit approximately 3 miles",
    aliases: ["leagues"],
  },
  "thou": {
    name: "Thou",
    symbol: "th",
    category: "length",
    toBase: 0.0000254,
    description: "One thousandth of an inch (mil)",
    aliases: ["mil", "mils", "thousandth of an inch"],
  },
  "parsec": {
    name: "Parsec",
    symbol: "pc",
    category: "length",
    toBase: 30856775814671900,
    description: "Astronomical unit based on parallax of one arcsecond",
    aliases: ["parsecs"],
  },
  "astronomical-unit": {
    name: "Astronomical Unit",
    symbol: "au",
    category: "length",
    toBase: 149597870700,
    description: "Mean Earth-Sun distance",
    aliases: ["AU", "astronomical units", "ua"],
  },

  // ======================================================================
  // 2. WEIGHT (base: kilogram)
  // ======================================================================
  "kilogram": {
    name: "Kilogram",
    symbol: "kg",
    category: "weight",
    toBase: 1,
    description: "SI base unit of mass",
    aliases: ["kilograms", "kilo", "kilos"],
  },
  "gram": {
    name: "Gram",
    symbol: "g",
    category: "weight",
    toBase: 0.001,
    description: "One thousandth of a kilogram",
    aliases: ["grams", "gramme", "grammes"],
  },
  "milligram": {
    name: "Milligram",
    symbol: "mg",
    category: "weight",
    toBase: 0.000001,
    description: "One thousandth of a gram",
    aliases: ["milligrams"],
  },
  "microgram": {
    name: "Microgram",
    symbol: "\u00b5g",
    category: "weight",
    toBase: 0.000000001,
    description: "One millionth of a gram",
    aliases: ["micrograms", "mcg"],
  },
  "metric-ton": {
    name: "Metric Ton",
    symbol: "t",
    category: "weight",
    toBase: 1000,
    description: "1,000 kilograms",
    aliases: ["tonne", "tonnes", "metric tons", "MT"],
  },
  "pound": {
    name: "Pound",
    symbol: "lb",
    category: "weight",
    toBase: 0.45359237,
    description: "Imperial unit of mass",
    aliases: ["pounds", "lbs", "lb"],
  },
  "ounce": {
    name: "Ounce",
    symbol: "oz",
    category: "weight",
    toBase: 0.028349523125,
    description: "1/16 of a pound (avoirdupois)",
    aliases: ["ounces", "oz"],
  },
  "stone": {
    name: "Stone",
    symbol: "st",
    category: "weight",
    toBase: 6.35029318,
    description: "Imperial unit equal to 14 pounds",
    aliases: ["stones"],
  },
  "short-ton": {
    name: "Short Ton",
    symbol: "ton",
    category: "weight",
    toBase: 907.18474,
    description: "US ton equal to 2,000 pounds",
    aliases: ["US ton", "short tons", "tons"],
  },
  "long-ton": {
    name: "Long Ton",
    symbol: "long tn",
    category: "weight",
    toBase: 1016.0469088,
    description: "Imperial ton equal to 2,240 pounds",
    aliases: ["imperial ton", "long tons"],
  },
  "carat": {
    name: "Carat",
    symbol: "ct",
    category: "weight",
    toBase: 0.0002,
    description: "Unit for gemstone weight (200 mg)",
    aliases: ["carats", "ct", "karat"],
  },
  "grain": {
    name: "Grain",
    symbol: "gr",
    category: "weight",
    toBase: 0.00006479891,
    description: "Historical unit, 1/7000 of a pound",
    aliases: ["grains"],
  },
  "troy-ounce": {
    name: "Troy Ounce",
    symbol: "oz t",
    category: "weight",
    toBase: 0.0311034768,
    description: "Unit for precious metals",
    aliases: ["troy ounces", "ozt"],
  },
  "slug": {
    name: "Slug",
    symbol: "slug",
    category: "weight",
    toBase: 14.593903,
    description: "Imperial unit of mass in the FPS system",
    aliases: ["slugs"],
  },

  // ======================================================================
  // 3. TEMPERATURE (base: kelvin)
  // Non-linear conversions -- toBase is 1 placeholder.
  // Actual conversion handled by FORMULAS.
  // ======================================================================
  "celsius": {
    name: "Celsius",
    symbol: "\u00b0C",
    category: "temperature",
    toBase: 1,
    description: "Metric temperature scale (water freezes at 0, boils at 100)",
    aliases: ["centigrade", "C", "deg C"],
  },
  "fahrenheit": {
    name: "Fahrenheit",
    symbol: "\u00b0F",
    category: "temperature",
    toBase: 1,
    description: "Imperial temperature scale (water freezes at 32, boils at 212)",
    aliases: ["F", "deg F"],
  },
  "kelvin": {
    name: "Kelvin",
    symbol: "K",
    category: "temperature",
    toBase: 1,
    description: "SI base unit of thermodynamic temperature",
    aliases: ["kelvins"],
  },
  "rankine": {
    name: "Rankine",
    symbol: "\u00b0R",
    category: "temperature",
    toBase: 1,
    description: "Absolute scale based on Fahrenheit degrees",
    aliases: ["R", "deg R", "rankines"],
  },

  // ======================================================================
  // 4. VOLUME (base: liter)
  // ======================================================================
  "liter": {
    name: "Liter",
    symbol: "L",
    category: "volume",
    toBase: 1,
    description: "Metric unit of volume equal to 1 cubic decimeter",
    aliases: ["litre", "liters", "litres"],
  },
  "milliliter": {
    name: "Milliliter",
    symbol: "mL",
    category: "volume",
    toBase: 0.001,
    description: "One thousandth of a liter",
    aliases: ["millilitre", "milliliters", "millilitres", "cc"],
  },
  "cubic-meter": {
    name: "Cubic Meter",
    symbol: "m\u00b3",
    category: "volume",
    toBase: 1000,
    description: "SI derived unit of volume",
    aliases: ["cubic metre", "cubic meters", "cubic metres", "m3"],
  },
  "cubic-centimeter": {
    name: "Cubic Centimeter",
    symbol: "cm\u00b3",
    category: "volume",
    toBase: 0.001,
    description: "Volume of a 1 cm cube, equal to 1 milliliter",
    aliases: ["cubic centimetre", "cc", "cm3"],
  },
  "gallon-us": {
    name: "US Gallon",
    symbol: "gal",
    category: "volume",
    toBase: 3.785411784,
    description: "US liquid gallon (231 cubic inches)",
    aliases: ["US gallon", "US gallons", "gal US"],
  },
  "gallon-uk": {
    name: "Imperial Gallon",
    symbol: "gal",
    category: "volume",
    toBase: 4.54609,
    description: "Imperial (UK) gallon",
    aliases: ["UK gallon", "imperial gallon", "imperial gallons", "gal UK"],
  },
  "quart-us": {
    name: "US Quart",
    symbol: "qt",
    category: "volume",
    toBase: 0.946352946,
    description: "US liquid quart (1/4 US gallon)",
    aliases: ["US quart", "US quarts", "qt US"],
  },
  "pint-us": {
    name: "US Pint",
    symbol: "pt",
    category: "volume",
    toBase: 0.473176473,
    description: "US liquid pint (1/8 US gallon)",
    aliases: ["US pint", "US pints", "pt US"],
  },
  "cup-us": {
    name: "US Cup",
    symbol: "cup",
    category: "volume",
    toBase: 0.2365882365,
    description: "US customary cup (8 US fluid ounces)",
    aliases: ["US cup", "US cups"],
  },
  "fluid-ounce-us": {
    name: "US Fluid Ounce",
    symbol: "fl oz",
    category: "volume",
    toBase: 0.0295735295625,
    description: "US fluid ounce (1/128 US gallon)",
    aliases: ["US fluid ounce", "US fluid ounces", "fl oz US"],
  },
  "tablespoon-us": {
    name: "US Tablespoon",
    symbol: "tbsp",
    category: "volume",
    toBase: 0.01478676478125,
    description: "US tablespoon (1/2 US fluid ounce)",
    aliases: ["US tablespoon", "US tablespoons", "tbsp US", "Tbsp"],
  },
  "teaspoon-us": {
    name: "US Teaspoon",
    symbol: "tsp",
    category: "volume",
    toBase: 0.00492892159375,
    description: "US teaspoon (1/6 US fluid ounce)",
    aliases: ["US teaspoon", "US teaspoons", "tsp US"],
  },
  "quart-uk": {
    name: "Imperial Quart",
    symbol: "qt",
    category: "volume",
    toBase: 1.1365225,
    description: "Imperial (UK) quart",
    aliases: ["UK quart", "imperial quart", "qt UK"],
  },
  "pint-uk": {
    name: "Imperial Pint",
    symbol: "pt",
    category: "volume",
    toBase: 0.56826125,
    description: "Imperial (UK) pint",
    aliases: ["UK pint", "imperial pint", "pt UK"],
  },
  "fluid-ounce-uk": {
    name: "Imperial Fluid Ounce",
    symbol: "fl oz",
    category: "volume",
    toBase: 0.0284130625,
    description: "Imperial (UK) fluid ounce",
    aliases: ["UK fluid ounce", "imperial fluid ounce", "fl oz UK"],
  },
  "cubic-inch": {
    name: "Cubic Inch",
    symbol: "in\u00b3",
    category: "volume",
    toBase: 0.016387064,
    description: "Volume of a 1-inch cube",
    aliases: ["cubic inches", "cu in", "in3"],
  },
  "cubic-foot": {
    name: "Cubic Foot",
    symbol: "ft\u00b3",
    category: "volume",
    toBase: 28.316846592,
    description: "Volume of a 1-foot cube",
    aliases: ["cubic feet", "cu ft", "ft3"],
  },
  "cubic-yard": {
    name: "Cubic Yard",
    symbol: "yd\u00b3",
    category: "volume",
    toBase: 764.554857984,
    description: "Volume of a 1-yard cube",
    aliases: ["cubic yards", "cu yd", "yd3"],
  },
  "barrel-oil": {
    name: "Barrel (Oil)",
    symbol: "bbl",
    category: "volume",
    toBase: 158.987294928,
    description: "Standard petroleum barrel (42 US gallons)",
    aliases: ["oil barrel", "barrels", "bbl"],
  },

  // ======================================================================
  // 5. AREA (base: square-meter)
  // ======================================================================
  "square-meter": {
    name: "Square Meter",
    symbol: "m\u00b2",
    category: "area",
    toBase: 1,
    description: "SI derived unit of area",
    aliases: ["square metre", "sq m", "m2"],
  },
  "square-kilometer": {
    name: "Square Kilometer",
    symbol: "km\u00b2",
    category: "area",
    toBase: 1000000,
    description: "Area of a 1 km square",
    aliases: ["square kilometre", "sq km", "km2"],
  },
  "square-centimeter": {
    name: "Square Centimeter",
    symbol: "cm\u00b2",
    category: "area",
    toBase: 0.0001,
    description: "Area of a 1 cm square",
    aliases: ["square centimetre", "sq cm", "cm2"],
  },
  "square-millimeter": {
    name: "Square Millimeter",
    symbol: "mm\u00b2",
    category: "area",
    toBase: 0.000001,
    description: "Area of a 1 mm square",
    aliases: ["square millimetre", "sq mm", "mm2"],
  },
  "hectare": {
    name: "Hectare",
    symbol: "ha",
    category: "area",
    toBase: 10000,
    description: "Metric unit equal to 10,000 square meters",
    aliases: ["hectares"],
  },
  "acre": {
    name: "Acre",
    symbol: "ac",
    category: "area",
    toBase: 4046.8564224,
    description: "Imperial/US unit of land area",
    aliases: ["acres"],
  },
  "square-mile": {
    name: "Square Mile",
    symbol: "mi\u00b2",
    category: "area",
    toBase: 2589988.110336,
    description: "Area of a 1-mile square (640 acres)",
    aliases: ["sq mi", "mi2", "square miles"],
  },
  "square-yard": {
    name: "Square Yard",
    symbol: "yd\u00b2",
    category: "area",
    toBase: 0.83612736,
    description: "Area of a 1-yard square",
    aliases: ["sq yd", "yd2", "square yards"],
  },
  "square-foot": {
    name: "Square Foot",
    symbol: "ft\u00b2",
    category: "area",
    toBase: 0.09290304,
    description: "Area of a 1-foot square",
    aliases: ["sq ft", "ft2", "square feet"],
  },
  "square-inch": {
    name: "Square Inch",
    symbol: "in\u00b2",
    category: "area",
    toBase: 0.00064516,
    description: "Area of a 1-inch square",
    aliases: ["sq in", "in2", "square inches"],
  },
  "pyeong": {
    name: "Pyeong",
    symbol: "\ud3c9",
    category: "area",
    toBase: 3.305785,
    description: "Korean traditional unit of area",
    aliases: ["\ud3c9", "pyeongs", "\ud3c9\ubc29\ubbf8\ud130"],
  },
  "tsubo": {
    name: "Tsubo",
    symbol: "\u5764",
    category: "area",
    toBase: 3.305785,
    description: "Japanese traditional unit of area (same as pyeong)",
    aliases: ["\u5764", "tsubos"],
  },

  // ======================================================================
  // 6. SPEED (base: meter-per-second)
  // ======================================================================
  "meter-per-second": {
    name: "Meter per Second",
    symbol: "m/s",
    category: "speed",
    toBase: 1,
    description: "SI derived unit of speed",
    aliases: ["metres per second", "m/sec", "mps"],
  },
  "kilometer-per-hour": {
    name: "Kilometer per Hour",
    symbol: "km/h",
    category: "speed",
    toBase: 0.2777777777777778,
    description: "Common metric speed unit",
    aliases: ["kph", "kmh", "km/hr", "kilometres per hour"],
  },
  "mile-per-hour": {
    name: "Mile per Hour",
    symbol: "mph",
    category: "speed",
    toBase: 0.44704,
    description: "Imperial speed unit",
    aliases: ["miles per hour", "mi/h"],
  },
  "knot": {
    name: "Knot",
    symbol: "kn",
    category: "speed",
    toBase: 0.5144444444444444,
    description: "Nautical speed unit (1 nautical mile per hour)",
    aliases: ["knots", "kt", "kts"],
  },
  "foot-per-second": {
    name: "Foot per Second",
    symbol: "ft/s",
    category: "speed",
    toBase: 0.3048,
    description: "Imperial speed unit",
    aliases: ["feet per second", "fps", "ft/sec"],
  },
  "mach": {
    name: "Mach",
    symbol: "Ma",
    category: "speed",
    toBase: 343,
    description: "Speed relative to the speed of sound in dry air at 20\u00b0C",
    aliases: ["mach number", "Ma"],
  },
  "speed-of-light": {
    name: "Speed of Light",
    symbol: "c",
    category: "speed",
    toBase: 299792458,
    description: "Speed of light in vacuum",
    aliases: ["c", "light speed"],
  },

  // ======================================================================
  // 7. TIME (base: second)
  // ======================================================================
  "second": {
    name: "Second",
    symbol: "s",
    category: "time",
    toBase: 1,
    description: "SI base unit of time",
    aliases: ["seconds", "sec", "secs"],
  },
  "millisecond": {
    name: "Millisecond",
    symbol: "ms",
    category: "time",
    toBase: 0.001,
    description: "One thousandth of a second",
    aliases: ["milliseconds", "msec"],
  },
  "microsecond": {
    name: "Microsecond",
    symbol: "\u00b5s",
    category: "time",
    toBase: 0.000001,
    description: "One millionth of a second",
    aliases: ["microseconds", "usec"],
  },
  "nanosecond": {
    name: "Nanosecond",
    symbol: "ns",
    category: "time",
    toBase: 0.000000001,
    description: "One billionth of a second",
    aliases: ["nanoseconds", "nsec"],
  },
  "minute": {
    name: "Minute",
    symbol: "min",
    category: "time",
    toBase: 60,
    description: "60 seconds",
    aliases: ["minutes", "mins"],
  },
  "hour": {
    name: "Hour",
    symbol: "h",
    category: "time",
    toBase: 3600,
    description: "60 minutes",
    aliases: ["hours", "hr", "hrs"],
  },
  "day": {
    name: "Day",
    symbol: "d",
    category: "time",
    toBase: 86400,
    description: "24 hours",
    aliases: ["days"],
  },
  "week": {
    name: "Week",
    symbol: "wk",
    category: "time",
    toBase: 604800,
    description: "7 days",
    aliases: ["weeks", "wks"],
  },
  "month": {
    name: "Month",
    symbol: "mo",
    category: "time",
    toBase: 2629746,
    description: "Average month (1/12 of a Julian year = 30.436875 days)",
    aliases: ["months", "mos"],
  },
  "year": {
    name: "Year",
    symbol: "yr",
    category: "time",
    toBase: 31556952,
    description: "Julian year (365.25 days)",
    aliases: ["years", "yrs"],
  },
  "decade": {
    name: "Decade",
    symbol: "dec",
    category: "time",
    toBase: 315569520,
    description: "10 years",
    aliases: ["decades"],
  },
  "century": {
    name: "Century",
    symbol: "c",
    category: "time",
    toBase: 3155695200,
    description: "100 years",
    aliases: ["centuries"],
  },
  "millennium": {
    name: "Millennium",
    symbol: "ky",
    category: "time",
    toBase: 31556952000,
    description: "1,000 years",
    aliases: ["millennia", "millenniums"],
  },

  // ======================================================================
  // 8. DATA STORAGE (base: byte)
  // ======================================================================
  "byte": {
    name: "Byte",
    symbol: "B",
    category: "data-storage",
    toBase: 1,
    description: "Basic unit of digital information (8 bits)",
    aliases: ["bytes"],
  },
  "kilobyte": {
    name: "Kilobyte",
    symbol: "KB",
    category: "data-storage",
    toBase: 1000,
    description: "1,000 bytes (SI)",
    aliases: ["kilobytes", "kB"],
  },
  "megabyte": {
    name: "Megabyte",
    symbol: "MB",
    category: "data-storage",
    toBase: 1000000,
    description: "1,000,000 bytes (SI)",
    aliases: ["megabytes"],
  },
  "gigabyte": {
    name: "Gigabyte",
    symbol: "GB",
    category: "data-storage",
    toBase: 1000000000,
    description: "1,000,000,000 bytes (SI)",
    aliases: ["gigabytes"],
  },
  "terabyte": {
    name: "Terabyte",
    symbol: "TB",
    category: "data-storage",
    toBase: 1000000000000,
    description: "1,000,000,000,000 bytes (SI)",
    aliases: ["terabytes"],
  },
  "petabyte": {
    name: "Petabyte",
    symbol: "PB",
    category: "data-storage",
    toBase: 1000000000000000,
    description: "1,000,000,000,000,000 bytes (SI)",
    aliases: ["petabytes"],
  },
  "exabyte": {
    name: "Exabyte",
    symbol: "EB",
    category: "data-storage",
    toBase: 1000000000000000000,
    description: "1,000,000,000,000,000,000 bytes (SI)",
    aliases: ["exabytes"],
  },
  "kibibyte": {
    name: "Kibibyte",
    symbol: "KiB",
    category: "data-storage",
    toBase: 1024,
    description: "1,024 bytes (binary)",
    aliases: ["kibibytes"],
  },
  "mebibyte": {
    name: "Mebibyte",
    symbol: "MiB",
    category: "data-storage",
    toBase: 1048576,
    description: "1,048,576 bytes (binary)",
    aliases: ["mebibytes"],
  },
  "gibibyte": {
    name: "Gibibyte",
    symbol: "GiB",
    category: "data-storage",
    toBase: 1073741824,
    description: "1,073,741,824 bytes (binary)",
    aliases: ["gibibytes"],
  },
  "tebibyte": {
    name: "Tebibyte",
    symbol: "TiB",
    category: "data-storage",
    toBase: 1099511627776,
    description: "1,099,511,627,776 bytes (binary)",
    aliases: ["tebibytes"],
  },
  "pebibyte": {
    name: "Pebibyte",
    symbol: "PiB",
    category: "data-storage",
    toBase: 1125899906842624,
    description: "1,125,899,906,842,624 bytes (binary)",
    aliases: ["pebibytes"],
  },
  "bit": {
    name: "Bit",
    symbol: "b",
    category: "data-storage",
    toBase: 0.125,
    description: "Single binary digit (1/8 byte)",
    aliases: ["bits"],
  },
  "kilobit": {
    name: "Kilobit",
    symbol: "kb",
    category: "data-storage",
    toBase: 125,
    description: "1,000 bits",
    aliases: ["kilobits", "Kb"],
  },
  "megabit": {
    name: "Megabit",
    symbol: "Mb",
    category: "data-storage",
    toBase: 125000,
    description: "1,000,000 bits",
    aliases: ["megabits"],
  },
  "gigabit": {
    name: "Gigabit",
    symbol: "Gb",
    category: "data-storage",
    toBase: 125000000,
    description: "1,000,000,000 bits",
    aliases: ["gigabits"],
  },

  // ======================================================================
  // 9. PRESSURE (base: pascal)
  // ======================================================================
  "pascal": {
    name: "Pascal",
    symbol: "Pa",
    category: "pressure",
    toBase: 1,
    description: "SI derived unit of pressure (1 N/m\u00b2)",
    aliases: ["pascals"],
  },
  "kilopascal": {
    name: "Kilopascal",
    symbol: "kPa",
    category: "pressure",
    toBase: 1000,
    description: "1,000 pascals",
    aliases: ["kilopascals"],
  },
  "megapascal": {
    name: "Megapascal",
    symbol: "MPa",
    category: "pressure",
    toBase: 1000000,
    description: "1,000,000 pascals",
    aliases: ["megapascals"],
  },
  "bar": {
    name: "Bar",
    symbol: "bar",
    category: "pressure",
    toBase: 100000,
    description: "Metric unit roughly equal to atmospheric pressure",
    aliases: ["bars"],
  },
  "millibar": {
    name: "Millibar",
    symbol: "mbar",
    category: "pressure",
    toBase: 100,
    description: "One thousandth of a bar (equal to 1 hPa)",
    aliases: ["millibars", "mb", "hectopascal", "hPa"],
  },
  "atmosphere": {
    name: "Atmosphere",
    symbol: "atm",
    category: "pressure",
    toBase: 101325,
    description: "Standard atmospheric pressure at sea level",
    aliases: ["atmospheres", "standard atmosphere"],
  },
  "torr": {
    name: "Torr",
    symbol: "Torr",
    category: "pressure",
    toBase: 133.3223684211,
    description: "Approximately 1/760 of an atmosphere",
    aliases: ["torrs"],
  },
  "psi": {
    name: "Pounds per Square Inch",
    symbol: "psi",
    category: "pressure",
    toBase: 6894.757293168,
    description: "Imperial pressure unit",
    aliases: ["PSI", "lb/in\u00b2", "lbf/in\u00b2"],
  },
  "mmhg": {
    name: "Millimeters of Mercury",
    symbol: "mmHg",
    category: "pressure",
    toBase: 133.322387415,
    description: "Pressure exerted by 1 mm column of mercury",
    aliases: ["mm Hg", "millimeters of mercury", "mmHg"],
  },

  // ======================================================================
  // 10. ENERGY (base: joule)
  // ======================================================================
  "joule": {
    name: "Joule",
    symbol: "J",
    category: "energy",
    toBase: 1,
    description: "SI derived unit of energy",
    aliases: ["joules"],
  },
  "kilojoule": {
    name: "Kilojoule",
    symbol: "kJ",
    category: "energy",
    toBase: 1000,
    description: "1,000 joules",
    aliases: ["kilojoules"],
  },
  "megajoule": {
    name: "Megajoule",
    symbol: "MJ",
    category: "energy",
    toBase: 1000000,
    description: "1,000,000 joules",
    aliases: ["megajoules"],
  },
  "calorie": {
    name: "Calorie (thermochemical)",
    symbol: "cal",
    category: "energy",
    toBase: 4.184,
    description: "Energy to raise 1 g water by 1\u00b0C (thermochemical)",
    aliases: ["calories", "small calorie", "gram calorie"],
  },
  "kilocalorie": {
    name: "Kilocalorie",
    symbol: "kcal",
    category: "energy",
    toBase: 4184,
    description: "1,000 calories (food Calorie)",
    aliases: ["kilocalories", "Cal", "food calorie", "large calorie"],
  },
  "watt-hour": {
    name: "Watt-hour",
    symbol: "Wh",
    category: "energy",
    toBase: 3600,
    description: "Energy of 1 watt sustained for 1 hour",
    aliases: ["watt-hours", "watt hours"],
  },
  "kilowatt-hour": {
    name: "Kilowatt-hour",
    symbol: "kWh",
    category: "energy",
    toBase: 3600000,
    description: "Common unit for electrical energy billing",
    aliases: ["kilowatt-hours", "kilowatt hours", "kW\u00b7h"],
  },
  "btu": {
    name: "British Thermal Unit",
    symbol: "BTU",
    category: "energy",
    toBase: 1055.05585262,
    description: "Energy to raise 1 lb water by 1\u00b0F",
    aliases: ["BTU", "BTUs", "british thermal unit", "british thermal units"],
  },
  "electronvolt": {
    name: "Electronvolt",
    symbol: "eV",
    category: "energy",
    toBase: 1.602176634e-19,
    description: "Energy gained by an electron through 1 volt potential",
    aliases: ["electronvolts", "electron volt", "electron-volt"],
  },
  "therm": {
    name: "Therm",
    symbol: "thm",
    category: "energy",
    toBase: 105505585.262,
    description: "100,000 BTU, used in natural gas billing",
    aliases: ["therms"],
  },
  "foot-pound": {
    name: "Foot-pound",
    symbol: "ft\u00b7lbf",
    category: "energy",
    toBase: 1.3558179483314,
    description: "Energy to raise 1 pound by 1 foot",
    aliases: ["foot-pounds", "ft-lbf", "ft lbf"],
  },

  // ======================================================================
  // 11. FREQUENCY (base: hertz)
  // ======================================================================
  "hertz": {
    name: "Hertz",
    symbol: "Hz",
    category: "frequency",
    toBase: 1,
    description: "SI unit of frequency (cycles per second)",
    aliases: ["hz"],
  },
  "kilohertz": {
    name: "Kilohertz",
    symbol: "kHz",
    category: "frequency",
    toBase: 1000,
    description: "1,000 hertz",
    aliases: ["kilohertz", "kHz"],
  },
  "megahertz": {
    name: "Megahertz",
    symbol: "MHz",
    category: "frequency",
    toBase: 1000000,
    description: "1,000,000 hertz",
    aliases: ["megahertz", "MHz"],
  },
  "gigahertz": {
    name: "Gigahertz",
    symbol: "GHz",
    category: "frequency",
    toBase: 1000000000,
    description: "1,000,000,000 hertz",
    aliases: ["gigahertz", "GHz"],
  },
  "terahertz": {
    name: "Terahertz",
    symbol: "THz",
    category: "frequency",
    toBase: 1000000000000,
    description: "1,000,000,000,000 hertz",
    aliases: ["terahertz", "THz"],
  },
  "rpm": {
    name: "Revolutions per Minute",
    symbol: "rpm",
    category: "frequency",
    toBase: 0.0166666666666667,
    description: "Rotational frequency (1/60 Hz)",
    aliases: ["RPM", "rev/min"],
  },

  // ======================================================================
  // 12. FORCE (base: newton)
  // ======================================================================
  "newton": {
    name: "Newton",
    symbol: "N",
    category: "force",
    toBase: 1,
    description: "SI derived unit of force (kg\u00b7m/s\u00b2)",
    aliases: ["newtons"],
  },
  "kilonewton": {
    name: "Kilonewton",
    symbol: "kN",
    category: "force",
    toBase: 1000,
    description: "1,000 newtons",
    aliases: ["kilonewtons"],
  },
  "meganewton": {
    name: "Meganewton",
    symbol: "MN",
    category: "force",
    toBase: 1000000,
    description: "1,000,000 newtons",
    aliases: ["meganewtons"],
  },
  "dyne": {
    name: "Dyne",
    symbol: "dyn",
    category: "force",
    toBase: 0.00001,
    description: "CGS unit of force (g\u00b7cm/s\u00b2)",
    aliases: ["dynes"],
  },
  "pound-force": {
    name: "Pound-force",
    symbol: "lbf",
    category: "force",
    toBase: 4.4482216152605,
    description: "Force of gravity on one avoirdupois pound",
    aliases: ["pounds-force", "lbf"],
  },
  "kilogram-force": {
    name: "Kilogram-force",
    symbol: "kgf",
    category: "force",
    toBase: 9.80665,
    description: "Force of gravity on one kilogram",
    aliases: ["kilopond", "kp", "kilogram-forces"],
  },
  "kip": {
    name: "Kip",
    symbol: "kip",
    category: "force",
    toBase: 4448.2216152605,
    description: "1,000 pounds-force",
    aliases: ["kips", "kilopound-force"],
  },

  // ======================================================================
  // 13. POWER (base: watt)
  // ======================================================================
  "watt": {
    name: "Watt",
    symbol: "W",
    category: "power",
    toBase: 1,
    description: "SI derived unit of power (J/s)",
    aliases: ["watts"],
  },
  "kilowatt": {
    name: "Kilowatt",
    symbol: "kW",
    category: "power",
    toBase: 1000,
    description: "1,000 watts",
    aliases: ["kilowatts"],
  },
  "megawatt": {
    name: "Megawatt",
    symbol: "MW",
    category: "power",
    toBase: 1000000,
    description: "1,000,000 watts",
    aliases: ["megawatts"],
  },
  "gigawatt": {
    name: "Gigawatt",
    symbol: "GW",
    category: "power",
    toBase: 1000000000,
    description: "1,000,000,000 watts",
    aliases: ["gigawatts"],
  },
  "horsepower": {
    name: "Horsepower (mechanical)",
    symbol: "hp",
    category: "power",
    toBase: 745.69987158227,
    description: "Mechanical/imperial horsepower (550 ft\u00b7lbf/s)",
    aliases: ["HP", "hp(I)", "mechanical horsepower"],
  },
  "horsepower-metric": {
    name: "Horsepower (metric)",
    symbol: "PS",
    category: "power",
    toBase: 735.49875,
    description: "Metric horsepower (75 kgf\u00b7m/s)",
    aliases: ["PS", "CV", "metric horsepower", "pferdest\u00e4rke"],
  },
  "btu-per-hour": {
    name: "BTU per Hour",
    symbol: "BTU/h",
    category: "power",
    toBase: 0.29307107017222,
    description: "Common HVAC power unit",
    aliases: ["BTU/hr", "BTUH"],
  },
  "foot-pound-per-second": {
    name: "Foot-pound per Second",
    symbol: "ft\u00b7lbf/s",
    category: "power",
    toBase: 1.3558179483314,
    description: "Imperial unit of power",
    aliases: ["ft-lbf/s"],
  },
  "ton-of-refrigeration": {
    name: "Ton of Refrigeration",
    symbol: "TR",
    category: "power",
    toBase: 3516.8528420667,
    description: "Cooling power (12,000 BTU/h)",
    aliases: ["tons of refrigeration", "RT"],
  },

  // ======================================================================
  // 14. ANGLE (base: radian)
  // ======================================================================
  "radian": {
    name: "Radian",
    symbol: "rad",
    category: "angle",
    toBase: 1,
    description: "SI unit of angular measure",
    aliases: ["radians"],
  },
  "degree": {
    name: "Degree",
    symbol: "\u00b0",
    category: "angle",
    toBase: 0.0174532925199433,
    description: "1/360 of a full rotation",
    aliases: ["degrees", "deg"],
  },
  "gradian": {
    name: "Gradian",
    symbol: "gon",
    category: "angle",
    toBase: 0.0157079632679490,
    description: "1/400 of a full rotation (grad)",
    aliases: ["gradians", "grad", "grade", "gon"],
  },
  "arcminute": {
    name: "Arcminute",
    symbol: "\u2032",
    category: "angle",
    toBase: 0.000290888208665722,
    description: "1/60 of a degree",
    aliases: ["arcminutes", "minute of arc", "MOA"],
  },
  "arcsecond": {
    name: "Arcsecond",
    symbol: "\u2033",
    category: "angle",
    toBase: 0.00000484813681109536,
    description: "1/3600 of a degree",
    aliases: ["arcseconds", "second of arc"],
  },
  "milliradian": {
    name: "Milliradian",
    symbol: "mrad",
    category: "angle",
    toBase: 0.001,
    description: "One thousandth of a radian",
    aliases: ["milliradians", "mil"],
  },
  "turn": {
    name: "Turn",
    symbol: "tr",
    category: "angle",
    toBase: 6.28318530717959,
    description: "Full rotation (2\u03c0 radians)",
    aliases: ["turns", "full turn", "cycle", "rotation"],
  },
  "revolution": {
    name: "Revolution",
    symbol: "rev",
    category: "angle",
    toBase: 6.28318530717959,
    description: "Full rotation, same as turn",
    aliases: ["revolutions", "revs"],
  },

  // ======================================================================
  // 15. FUEL ECONOMY (base: km-per-liter)
  // ======================================================================
  "km-per-liter": {
    name: "Kilometers per Liter",
    symbol: "km/L",
    category: "fuel-economy",
    toBase: 1,
    description: "Metric fuel economy measure",
    aliases: ["km/l", "kilometres per litre", "kmpl"],
  },
  "mile-per-gallon-us": {
    name: "Miles per Gallon (US)",
    symbol: "mpg",
    category: "fuel-economy",
    toBase: 0.425143707,
    description: "US fuel economy measure (1 mpg = 0.425144 km/L)",
    aliases: ["mpg US", "mpg", "miles per gallon"],
  },
  "mile-per-gallon-uk": {
    name: "Miles per Gallon (UK)",
    symbol: "mpg",
    category: "fuel-economy",
    toBase: 0.354006044,
    description: "Imperial fuel economy measure",
    aliases: ["mpg UK", "mpg imperial"],
  },
  "liter-per-100km": {
    name: "Liters per 100 km",
    symbol: "L/100km",
    category: "fuel-economy",
    toBase: 1,
    description: "Inverse fuel economy (lower is better). Conversion handled by engine.",
    aliases: ["l/100km", "litres per 100 km", "L/100 km"],
  },

  // ======================================================================
  // 16. DATA TRANSFER (base: bit-per-second)
  // ======================================================================
  "bit-per-second": {
    name: "Bit per Second",
    symbol: "bps",
    category: "data-transfer",
    toBase: 1,
    description: "Base unit of data transfer rate",
    aliases: ["bps", "bits per second", "b/s"],
  },
  "kilobit-per-second": {
    name: "Kilobit per Second",
    symbol: "kbps",
    category: "data-transfer",
    toBase: 1000,
    description: "1,000 bits per second",
    aliases: ["kbps", "Kbps", "kb/s"],
  },
  "megabit-per-second": {
    name: "Megabit per Second",
    symbol: "Mbps",
    category: "data-transfer",
    toBase: 1000000,
    description: "1,000,000 bits per second",
    aliases: ["Mbps", "Mb/s"],
  },
  "gigabit-per-second": {
    name: "Gigabit per Second",
    symbol: "Gbps",
    category: "data-transfer",
    toBase: 1000000000,
    description: "1,000,000,000 bits per second",
    aliases: ["Gbps", "Gb/s"],
  },
  "terabit-per-second": {
    name: "Terabit per Second",
    symbol: "Tbps",
    category: "data-transfer",
    toBase: 1000000000000,
    description: "1,000,000,000,000 bits per second",
    aliases: ["Tbps", "Tb/s"],
  },
  "byte-per-second": {
    name: "Byte per Second",
    symbol: "B/s",
    category: "data-transfer",
    toBase: 8,
    description: "8 bits per second",
    aliases: ["Bps", "bytes per second"],
  },
  "kilobyte-per-second": {
    name: "Kilobyte per Second",
    symbol: "KB/s",
    category: "data-transfer",
    toBase: 8000,
    description: "1,000 bytes per second",
    aliases: ["KBps", "kB/s"],
  },
  "megabyte-per-second": {
    name: "Megabyte per Second",
    symbol: "MB/s",
    category: "data-transfer",
    toBase: 8000000,
    description: "1,000,000 bytes per second",
    aliases: ["MBps"],
  },
  "gigabyte-per-second": {
    name: "Gigabyte per Second",
    symbol: "GB/s",
    category: "data-transfer",
    toBase: 8000000000,
    description: "1,000,000,000 bytes per second",
    aliases: ["GBps"],
  },

  // ======================================================================
  // 17. DENSITY (base: kg-per-cubic-meter)
  // ======================================================================
  "kg-per-cubic-meter": {
    name: "Kilogram per Cubic Meter",
    symbol: "kg/m\u00b3",
    category: "density",
    toBase: 1,
    description: "SI derived unit of density",
    aliases: ["kg/m3", "kilograms per cubic meter"],
  },
  "g-per-cubic-centimeter": {
    name: "Gram per Cubic Centimeter",
    symbol: "g/cm\u00b3",
    category: "density",
    toBase: 1000,
    description: "Common density unit (1 g/cm\u00b3 = 1000 kg/m\u00b3)",
    aliases: ["g/cc", "g/cm3", "grams per cubic centimeter"],
  },
  "kg-per-liter": {
    name: "Kilogram per Liter",
    symbol: "kg/L",
    category: "density",
    toBase: 1000,
    description: "1 kg/L = 1000 kg/m\u00b3",
    aliases: ["kg/l", "kilograms per litre"],
  },
  "lb-per-cubic-foot": {
    name: "Pound per Cubic Foot",
    symbol: "lb/ft\u00b3",
    category: "density",
    toBase: 16.018463374,
    description: "Imperial density unit",
    aliases: ["lb/ft3", "pounds per cubic foot", "pcf"],
  },
  "lb-per-cubic-inch": {
    name: "Pound per Cubic Inch",
    symbol: "lb/in\u00b3",
    category: "density",
    toBase: 27679.904710191,
    description: "Imperial density unit",
    aliases: ["lb/in3", "pounds per cubic inch", "pci"],
  },
  "lb-per-gallon-us": {
    name: "Pound per US Gallon",
    symbol: "lb/gal",
    category: "density",
    toBase: 119.826427317,
    description: "US liquid density unit",
    aliases: ["lb/gal US", "pounds per gallon"],
  },

  // ======================================================================
  // 18. TORQUE (base: newton-meter)
  // ======================================================================
  "newton-meter": {
    name: "Newton-meter",
    symbol: "N\u00b7m",
    category: "torque",
    toBase: 1,
    description: "SI unit of torque",
    aliases: ["Nm", "newton-metres", "newton meters"],
  },
  "kilonewton-meter": {
    name: "Kilonewton-meter",
    symbol: "kN\u00b7m",
    category: "torque",
    toBase: 1000,
    description: "1,000 newton-meters",
    aliases: ["kNm", "kilonewton-metres"],
  },
  "foot-pound-force": {
    name: "Foot-pound Force",
    symbol: "ft\u00b7lbf",
    category: "torque",
    toBase: 1.3558179483314,
    description: "Imperial torque unit",
    aliases: ["ft-lbf", "ft lbf", "foot-pounds force"],
  },
  "inch-pound-force": {
    name: "Inch-pound Force",
    symbol: "in\u00b7lbf",
    category: "torque",
    toBase: 0.1129848290276167,
    description: "Imperial torque unit (1/12 ft-lbf)",
    aliases: ["in-lbf", "in lbf", "inch-pounds force"],
  },
  "kilogram-force-meter": {
    name: "Kilogram-force Meter",
    symbol: "kgf\u00b7m",
    category: "torque",
    toBase: 9.80665,
    description: "Metric gravitational torque unit",
    aliases: ["kgf-m", "kgf m", "kilogram-force metres"],
  },
  "dyne-centimeter": {
    name: "Dyne-centimeter",
    symbol: "dyn\u00b7cm",
    category: "torque",
    toBase: 0.0000001,
    description: "CGS unit of torque",
    aliases: ["dyn-cm", "dyn cm", "dyne-centimetre"],
  },

  // ======================================================================
  // 19. COOKING (base: milliliter)
  // ======================================================================
  "cooking-milliliter": {
    name: "Milliliter",
    symbol: "mL",
    category: "cooking",
    toBase: 1,
    description: "Base metric cooking measure",
    aliases: ["ml", "millilitre", "millilitres", "cc"],
  },
  "cooking-liter": {
    name: "Liter",
    symbol: "L",
    category: "cooking",
    toBase: 1000,
    description: "1,000 milliliters",
    aliases: ["litre", "litres"],
  },
  "cooking-teaspoon": {
    name: "Teaspoon",
    symbol: "tsp",
    category: "cooking",
    toBase: 4.92892,
    description: "US cooking teaspoon",
    aliases: ["teaspoons", "tsp"],
  },
  "cooking-tablespoon": {
    name: "Tablespoon",
    symbol: "tbsp",
    category: "cooking",
    toBase: 14.7868,
    description: "US cooking tablespoon (3 teaspoons)",
    aliases: ["tablespoons", "tbsp", "Tbsp"],
  },
  "cooking-fluid-ounce": {
    name: "Fluid Ounce",
    symbol: "fl oz",
    category: "cooking",
    toBase: 29.5735,
    description: "US fluid ounce (2 tablespoons)",
    aliases: ["fluid ounces", "fl oz"],
  },
  "cooking-cup": {
    name: "Cup",
    symbol: "cup",
    category: "cooking",
    toBase: 236.588,
    description: "US cooking cup (8 fluid ounces)",
    aliases: ["cups"],
  },
  "cooking-pint": {
    name: "Pint",
    symbol: "pt",
    category: "cooking",
    toBase: 473.176,
    description: "US pint (2 cups)",
    aliases: ["pints"],
  },
  "cooking-quart": {
    name: "Quart",
    symbol: "qt",
    category: "cooking",
    toBase: 946.353,
    description: "US quart (4 cups)",
    aliases: ["quarts"],
  },
  "cooking-gallon": {
    name: "Gallon",
    symbol: "gal",
    category: "cooking",
    toBase: 3785.41,
    description: "US gallon (16 cups)",
    aliases: ["gallons"],
  },
  "cooking-drop": {
    name: "Drop",
    symbol: "drop",
    category: "cooking",
    toBase: 0.05,
    description: "Approximate volume of a single drop (~0.05 mL)",
    aliases: ["drops"],
  },
  "cooking-dash": {
    name: "Dash",
    symbol: "dash",
    category: "cooking",
    toBase: 0.616115,
    description: "1/8 teaspoon",
    aliases: ["dashes"],
  },
  "cooking-pinch": {
    name: "Pinch",
    symbol: "pinch",
    category: "cooking",
    toBase: 0.308058,
    description: "1/16 teaspoon",
    aliases: ["pinches"],
  },

  // ======================================================================
  // 20. TYPOGRAPHY (base: pixel at 96 DPI)
  // ======================================================================
  "pixel": {
    name: "Pixel",
    symbol: "px",
    category: "typography",
    toBase: 1,
    description: "CSS reference pixel at 96 DPI",
    aliases: ["pixels", "px"],
  },
  "point": {
    name: "Point",
    symbol: "pt",
    category: "typography",
    toBase: 1.333333333333333,
    description: "Typographic point (1/72 inch = 96/72 px)",
    aliases: ["points", "pt"],
  },
  "pica": {
    name: "Pica",
    symbol: "pc",
    category: "typography",
    toBase: 16,
    description: "Typographic pica (12 points = 16 px)",
    aliases: ["picas"],
  },
  "em": {
    name: "Em",
    symbol: "em",
    category: "typography",
    toBase: 16,
    description: "Relative to parent font size (default 16px)",
    aliases: ["ems"],
  },
  "rem": {
    name: "Rem",
    symbol: "rem",
    category: "typography",
    toBase: 16,
    description: "Relative to root font size (default 16px)",
    aliases: ["rems", "root em"],
  },
  "inch-type": {
    name: "Inch (CSS)",
    symbol: "in",
    category: "typography",
    toBase: 96,
    description: "CSS inch (96 px at reference DPI)",
    aliases: ["inches"],
  },
  "centimeter-type": {
    name: "Centimeter (CSS)",
    symbol: "cm",
    category: "typography",
    toBase: 37.7952755905512,
    description: "CSS centimeter (96/2.54 px)",
    aliases: ["centimeters", "centimetres"],
  },
  "millimeter-type": {
    name: "Millimeter (CSS)",
    symbol: "mm",
    category: "typography",
    toBase: 3.77952755905512,
    description: "CSS millimeter (96/25.4 px)",
    aliases: ["millimeters", "millimetres"],
  },
};

// ---------------------------------------------------------------------------
// Categories (20 measurement domains)
// ---------------------------------------------------------------------------

export const CATEGORIES: Record<string, CategoryDef> = {
  "length": {
    slug: "length",
    name: "Length",
    icon: "\uD83D\uDCCF",
    description: "Convert between meters, feet, inches, miles, and more",
    baseUnit: "meter",
    order: 1,
  },
  "weight": {
    slug: "weight",
    name: "Weight & Mass",
    icon: "\u2696\uFE0F",
    description: "Convert between kilograms, pounds, ounces, and more",
    baseUnit: "kilogram",
    order: 2,
  },
  "temperature": {
    slug: "temperature",
    name: "Temperature",
    icon: "\uD83C\uDF21\uFE0F",
    description: "Convert between Celsius, Fahrenheit, and Kelvin",
    baseUnit: "kelvin",
    order: 3,
  },
  "volume": {
    slug: "volume",
    name: "Volume",
    icon: "\uD83E\uDDEA",
    description: "Convert between liters, gallons, cups, and more",
    baseUnit: "liter",
    order: 4,
  },
  "area": {
    slug: "area",
    name: "Area",
    icon: "\uD83D\uDCD0",
    description: "Convert between square meters, acres, hectares",
    baseUnit: "square-meter",
    order: 5,
  },
  "speed": {
    slug: "speed",
    name: "Speed",
    icon: "\uD83C\uDFCE\uFE0F",
    description: "Convert between km/h, mph, m/s, knots",
    baseUnit: "meter-per-second",
    order: 6,
  },
  "time": {
    slug: "time",
    name: "Time",
    icon: "\u23F0",
    description: "Convert between seconds, minutes, hours, days, years",
    baseUnit: "second",
    order: 7,
  },
  "data-storage": {
    slug: "data-storage",
    name: "Data Storage",
    icon: "\uD83D\uDCBE",
    description: "Convert between bytes, KB, MB, GB, TB",
    baseUnit: "byte",
    order: 8,
  },
  "pressure": {
    slug: "pressure",
    name: "Pressure",
    icon: "\uD83D\uDD27",
    description: "Convert between Pascal, bar, atm, psi",
    baseUnit: "pascal",
    order: 9,
  },
  "energy": {
    slug: "energy",
    name: "Energy",
    icon: "\u26A1",
    description: "Convert between joules, calories, kWh, BTU",
    baseUnit: "joule",
    order: 10,
  },
  "frequency": {
    slug: "frequency",
    name: "Frequency",
    icon: "\uD83D\uDCE1",
    description: "Convert between Hz, kHz, MHz, GHz",
    baseUnit: "hertz",
    order: 11,
  },
  "force": {
    slug: "force",
    name: "Force",
    icon: "\uD83D\uDCAA",
    description: "Convert between Newton, pound-force, dyne",
    baseUnit: "newton",
    order: 12,
  },
  "power": {
    slug: "power",
    name: "Power",
    icon: "\uD83D\uDD0C",
    description: "Convert between watts, horsepower, BTU/h",
    baseUnit: "watt",
    order: 13,
  },
  "angle": {
    slug: "angle",
    name: "Angle",
    icon: "\uD83D\uDCD0",
    description: "Convert between degrees, radians, gradians",
    baseUnit: "radian",
    order: 14,
  },
  "fuel-economy": {
    slug: "fuel-economy",
    name: "Fuel Economy",
    icon: "\u26FD",
    description: "Convert between mpg, km/L, L/100km",
    baseUnit: "km-per-liter",
    order: 15,
  },
  "data-transfer": {
    slug: "data-transfer",
    name: "Data Transfer Rate",
    icon: "\uD83C\uDF10",
    description: "Convert between bps, Mbps, Gbps",
    baseUnit: "bit-per-second",
    order: 16,
  },
  "density": {
    slug: "density",
    name: "Density",
    icon: "\uD83E\uDDF1",
    description: "Convert between kg/m\u00b3, g/cm\u00b3, lb/ft\u00b3",
    baseUnit: "kg-per-cubic-meter",
    order: 17,
  },
  "torque": {
    slug: "torque",
    name: "Torque",
    icon: "\uD83D\uDD29",
    description: "Convert between Nm, ft-lb, kgf-m",
    baseUnit: "newton-meter",
    order: 18,
  },
  "cooking": {
    slug: "cooking",
    name: "Cooking",
    icon: "\uD83C\uDF73",
    description: "Convert between cups, tablespoons, teaspoons, ml",
    baseUnit: "milliliter",
    order: 19,
  },
  "typography": {
    slug: "typography",
    name: "Typography",
    icon: "\uD83D\uDD24",
    description: "Convert between pt, px, em, rem",
    baseUnit: "pixel",
    order: 20,
  },
};

// ---------------------------------------------------------------------------
// Non-linear conversion formulas (temperature)
// ---------------------------------------------------------------------------

export const FORMULAS: Record<string, Record<string, TemperatureFormula>> = {
  temperature: {
    celsius: {
      toBase: (c: number) => c + 273.15,
      fromBase: (k: number) => k - 273.15,
    },
    fahrenheit: {
      toBase: (f: number) => (f - 32) * 5 / 9 + 273.15,
      fromBase: (k: number) => (k - 273.15) * 9 / 5 + 32,
    },
    kelvin: {
      toBase: (k: number) => k,
      fromBase: (k: number) => k,
    },
    rankine: {
      toBase: (r: number) => r * 5 / 9,
      fromBase: (k: number) => k * 9 / 5,
    },
  },
};
